### ISSUE TITLE
Odczyt pliku XLS

### ISSUE THREAD

**Issue by amaz-e** [amaz-e/cracjam2030#5]

**Comment by Vovage0912** [comment]
if((row.getCell(1) == null) || (row.getCell(1).getCellType() == CellType.BLANK) || (row.getCell(1).getCellType() != CellType.STRING)) {
                    String message = "Wystąpił błąd podczas dodania recordu. Rząd: " + (row.getRowNum()+1) + " Arkusz: " + sheet.getSheetName() + " Plik: " + path;
                    Main.logger.addError(message);
                     continue;
                } else if((row.getCell(0) == null) || (row.getCell(0).getCellType() == CellType.BLANK) || (row.getCell(0).getCellType() != CellType.NUMERIC) || !DateUtil.isCellDateFormatted(row.getCell(0))) {
                    String message = "Wystąpił błąd podczas dodania recordu. Rząd: " + (row.getRowNum()+1) + " Komórka: " + " Arkusz: " + sheet.getSheetName() + " Plik: " + path;
                    Main.logger.addError(message);
                    continue;
                } else if ((row.getCell(2) == null) || (row.getCell(2).getCellType() == CellType.BLANK) || (row.getCell(2).getCellType() == CellType.NUMERIC)) {
                    String message = "Wystąpił błąd podczas dodania recordu. Rząd: " + (row.getRowNum()+1) + " Komórka: " + " Arkusz: " + sheet.getSheetName() + " Plik: " + path;
                    Main.logger.addError(message);
                    continue;
                }
